name: Release

on:
  push:
    tags:
      - "*.*"
      - "*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Print version info
        id: semver
        run: |
          make version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run checks
        run: |
          make ci

      - name: Build
        run: |
          GIT_TAG=$(git describe --exact-match --abbrev=0 2>/dev/null || echo "")
          git clone https://github.com/mongodb-js/compass.git
          cd compass
          git checkout ${GIT_TAG}
          npm run bootstrap
          rm -rf ./node_modules/puppeteer
          rm -rf ./.git
          cd ..
          make release
